#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Wed Sep 08 16:19:43 2004

#from wxPython.wx import *
import wx

import os
#BROWSEBUTTON=wxNewEventType()

class rwkdirchooserpanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: rwkdirchooserpanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.MyLabel = wx.StaticText(self, -1, "Directory")
        self.label_1 = wx.StaticText(self, -1, "label_1")
        self.DirectoryTextBox = wx.TextCtrl(self, -1, "")
        self.BrowseButton = wx.Button(self, -1, "Browse")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        # EVENT HANDLING
        self.Bind(wx.EVT_BUTTON, self.OnBrowseButton, self.BrowseButton)
        self.path=''
        self.setdir=0
    
    def __set_properties(self):
        # begin wxGlade: rwkdirchooserpanel.__set_properties
        self.label_1.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: rwkdirchooserpanel.__do_layout
        grid_sizer_4 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(self.MyLabel, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        grid_sizer_4.Add(self.label_1, 0, 0, 0)
        grid_sizer_4.Add(self.DirectoryTextBox, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        grid_sizer_4.Add(self.BrowseButton, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        self.SetAutoLayout(1)
        self.SetSizer(grid_sizer_4)
        grid_sizer_4.Fit(self)
        grid_sizer_4.SetSizeHints(self)
        grid_sizer_4.AddGrowableCol(0)
        # end wxGlade

    def OnBrowseButton(self,e):
    #--------------------------------------------------
    # wxLogMessage("dirchooser Browse Button Pushed")
    #-------------------------------------------------- 
        dlg = wx.DirDialog(self,"",self.GetDir(),wx.DD_NEW_DIR_BUTTON)
        success=dlg.ShowModal()
        if success== wx.ID_OK:
            path=dlg.GetPath()
            self.DirectoryTextBox.SetValue(path)
            self.path=path
            if self.setdir:
                os.chdir(path)
#                print('curdir='+os.getcwd())
        dlg.Destroy()
        e.Skip()
        return success
    

    def GetDir(self):
        dir=self.DirectoryTextBox.GetValue()
        return dir

    def GetPath(self):
        return self.GetDir()
    
    def SetDir(self,dir):
        self.DirectoryTextBox.SetValue(dir)
        self.path=dir

    def SetPath(self, path):
        self.SetDir(path)

    def SetLabel(self,newlabel):
        self.MyLabel.SetLabel(newlabel) 
# end of class rwkdirchooserpanel


