#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Mon Oct 04 15:46:38 2004
#from wxPython.wx import *
import wx

BROWSEBUTTON=wx.NewEventType()

class rwkSingleFileChooser(wx.Panel):
    def __init__(self, parent, *args, **kwds):
        # begin wxGlade: rwksinglefilechooser.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, parent, *args, **kwds)
        self.MyLabel = wx.StaticText(self, -1, "Filename")
        self.label_1 = wx.StaticText(self, -1, "label_1")
        self.DirectoryTextBox = wx.TextCtrl(self, -1, "")
        self.BrowseButton = wx.Button(self, BROWSEBUTTON, "Browse")
        self.parent = parent

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        # set defaults
        self.style=wx.OPEN
        self.message="Select file to open"
        self.defaultdir=""
        self.filter="All Files (*.*)|*.*"

        # EVENT HANDLING
        self.Bind(wx.EVT_BUTTON, self.OnBrowseButton,self.BrowseButton)
        self.BrowseEventId = BROWSEBUTTON

    def __set_properties(self):
        # begin wxGlade: rwksinglefilechooser.__set_properties
        self.label_1.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: rwksinglefilechooser.__do_layout
        grid_sizer_4 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(self.MyLabel, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        grid_sizer_4.Add(self.label_1, 0, 0, 0)
        grid_sizer_4.Add(self.DirectoryTextBox, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        grid_sizer_4.Add(self.BrowseButton, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetAutoLayout(1)
        self.SetSizer(grid_sizer_4)
        grid_sizer_4.Fit(self)
        grid_sizer_4.SetSizeHints(self)
        grid_sizer_4.AddGrowableCol(0)
        # end wxGlade


    def OnBrowseButton(self,e):
        #--------------------------------------------------
        # wxLogMessage("dirchooser Browse Button Pushed")
        #--------------------------------------------------  
        dlg = wx.FileDialog(self,self.message,self.defaultdir,"", self.filter,self.style)
        success=dlg.ShowModal()
        if success== wx.ID_OK:
            path=dlg.GetPath()
            self.DirectoryTextBox.SetValue(path)
        dlg.Destroy()
        return success

    def GetPath(self):
        dir=self.DirectoryTextBox.GetValue()
        return dir

    def SetDir(self,dir):
        self.DirectoryTextBox.SetValue(dir)

    def SetPath(self,path):
        self.SetDir(path)

    def SetLabel(self,newlabel):
        self.MyLabel.SetLabel(newlabel) 

# end of class rwksinglefilechooser


